// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using u21497682_HW01_API.Data;

#nullable disable

namespace u21497682_HW01_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250319101059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("u21497682_HW01_API.Models.Product", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_ID"));

                    b.Property<string>("Product_Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Product_Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Product_ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Product_ID = 1,
                            Product_Description = "High-performance running shoes designed with breathable mesh and a cushioned sole for maximum comfort and support. Features a sleek design and durable rubber outsole for traction on various surfaces.",
                            Product_Name = "Running Shoes",
                            Product_Price = 89.99m
                        },
                        new
                        {
                            Product_ID = 2,
                            Product_Description = "Sleek leather boots with elastic side panels for easy wear. Features a comfortable insole and durable rubber outsole, ideal for everyday wear.",
                            Product_Name = "Boots",
                            Product_Price = 89m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
