// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using u21497682_HW01_API.Data;

#nullable disable

namespace u21497682_HW01_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("u21497682_HW01_API.Models.Product", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_ID"));

                    b.Property<string>("Product_Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Product_Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Product_ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Product_ID = 1,
                            Product_Description = "High-performance running shoes designed with breathable mesh and a cushioned sole for maximum comfort and support. Features a sleek design and durable rubber outsole for traction on various surfaces.",
                            Product_Name = "Running Shoes",
                            Product_Price = 89.99m
                        },
                        new
                        {
                            Product_ID = 2,
                            Product_Description = "Sleek leather boots with elastic side panels for easy wear. Features a comfortable insole and durable rubber outsole, ideal for everyday wear.",
                            Product_Name = "Boots",
                            Product_Price = 89m
                        },
                        new
                        {
                            Product_ID = 3,
                            Product_Description = "A classic baseball cap with an adjustable strap and embroidered logo. Made of breathable cotton, perfect for casual wear and outdoor activities.",
                            Product_Name = "Baseball Cap",
                            Product_Price = 19.99m
                        },
                        new
                        {
                            Product_ID = 4,
                            Product_Description = "Flowing, floor-length maxi dress made from lightweight fabric. Features an adjustable strap design and a flattering A-line silhouette.",
                            Product_Name = "Maxi Dress",
                            Product_Price = 59.99m
                        },
                        new
                        {
                            Product_ID = 5,
                            Product_Description = "A pair of slim-fit chinos made from lightweight cotton with a bit of stretch. Features a clean, modern look suitable for both work and weekend wear.",
                            Product_Name = "Slim Fit Chinos",
                            Product_Price = 44.95m
                        },
                        new
                        {
                            Product_ID = 6,
                            Product_Description = "Cozy hoodie with a bold graphic print on the front. Made of soft cotton, perfect for lounging or casual outings.",
                            Product_Name = "Hoodie",
                            Product_Price = 49.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
